"""initial_schema

Revision ID: 0001
Revises: 
Create Date: 2026-07-30 19:57:44.563541
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_policies',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('scope_type', sa.String(length=64), nullable=False),
    sa.Column('scope_id', sa.String(length=32), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_policies_scope_id'), 'access_policies', ['scope_id'], unique=False)
    op.create_index(op.f('ix_access_policies_scope_type'), 'access_policies', ['scope_type'], unique=False)
    op.create_index(op.f('ix_access_policies_status'), 'access_policies', ['status'], unique=False)
    op.create_table('agents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('agent_type', sa.String(length=32), nullable=False),
    sa.Column('host_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('identity_fingerprint', sa.String(length=255), nullable=False),
    sa.Column('api_base_url', sa.String(length=1024), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('resolved_ip', sa.String(length=128), nullable=True),
    sa.Column('enrollment_state', sa.String(length=32), nullable=False),
    sa.Column('identity_certificate', sa.Text(), nullable=False),
    sa.Column('certificate_serial', sa.String(length=255), nullable=True),
    sa.Column('certificate_valid_not_before', sa.DateTime(timezone=True), nullable=True),
    sa.Column('certificate_valid_not_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agent_version', sa.String(length=64), nullable=True),
    sa.Column('sindri_version', sa.String(length=64), nullable=True),
    sa.Column('sindri_protocol_version', sa.String(length=32), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('boot_id', sa.String(length=255), nullable=True),
    sa.Column('queue_length', sa.Integer(), nullable=False),
    sa.Column('current_job_id', sa.String(length=128), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('environment', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('library_position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_agent_type'), 'agents', ['agent_type'], unique=False)
    op.create_index(op.f('ix_agents_certificate_serial'), 'agents', ['certificate_serial'], unique=False)
    op.create_index(op.f('ix_agents_domain'), 'agents', ['domain'], unique=False)
    op.create_index(op.f('ix_agents_enrollment_state'), 'agents', ['enrollment_state'], unique=False)
    op.create_index(op.f('ix_agents_host_id'), 'agents', ['host_id'], unique=False)
    op.create_index(op.f('ix_agents_identity_fingerprint'), 'agents', ['identity_fingerprint'], unique=False)
    op.create_index(op.f('ix_agents_library_position'), 'agents', ['library_position'], unique=False)
    op.create_index(op.f('ix_agents_status'), 'agents', ['status'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('actor_type', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_id'), 'audit_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_type'), 'audit_events', ['actor_type'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_target_id'), 'audit_events', ['target_id'], unique=False)
    op.create_index(op.f('ix_audit_events_target_type'), 'audit_events', ['target_type'], unique=False)
    op.create_table('backup_manifests',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('backup_id', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backup_manifests_backup_id'), 'backup_manifests', ['backup_id'], unique=False)
    op.create_index(op.f('ix_backup_manifests_entity_id'), 'backup_manifests', ['entity_id'], unique=False)
    op.create_index(op.f('ix_backup_manifests_entity_type'), 'backup_manifests', ['entity_type'], unique=False)
    op.create_table('certificate_denylist',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=True),
    sa.Column('fingerprint_sha256', sa.String(length=255), nullable=False),
    sa.Column('serial_number', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificate_denylist_agent_id'), 'certificate_denylist', ['agent_id'], unique=False)
    op.create_index(op.f('ix_certificate_denylist_fingerprint_sha256'), 'certificate_denylist', ['fingerprint_sha256'], unique=True)
    op.create_table('controller_identity',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('controller_id', sa.String(length=128), nullable=False),
    sa.Column('certificate_pem', sa.Text(), nullable=False),
    sa.Column('encrypted_private_key', sa.Text(), nullable=False),
    sa.Column('encryption_metadata', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_controller_identity_controller_id'), 'controller_identity', ['controller_id'], unique=True)
    op.create_index(op.f('ix_controller_identity_status'), 'controller_identity', ['status'], unique=False)
    op.create_table('objects',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('image_data', sa.Text(), nullable=False),
    sa.Column('image_media_type', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objects_entity_id'), 'objects', ['entity_id'], unique=True)
    op.create_index(op.f('ix_objects_kind'), 'objects', ['kind'], unique=False)
    op.create_table('pod_denylist',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('pod_id', sa.String(length=64), nullable=True),
    sa.Column('subject_id', sa.String(length=64), nullable=True),
    sa.Column('identifier_type', sa.String(length=64), nullable=False),
    sa.Column('identifier_value', sa.String(length=512), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier_type', 'identifier_value', name='uq_pod_denylist_identifier')
    )
    op.create_index(op.f('ix_pod_denylist_identifier_type'), 'pod_denylist', ['identifier_type'], unique=False)
    op.create_index(op.f('ix_pod_denylist_identifier_value'), 'pod_denylist', ['identifier_value'], unique=False)
    op.create_index(op.f('ix_pod_denylist_pod_id'), 'pod_denylist', ['pod_id'], unique=False)
    op.create_index(op.f('ix_pod_denylist_subject_id'), 'pod_denylist', ['subject_id'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.create_index(op.f('ix_system_settings_scope'), 'system_settings', ['scope'], unique=False)
    op.create_table('agent_assignments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('block_id', sa.String(length=128), nullable=False),
    sa.Column('block_type', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'block_id', 'block_type', name='uq_agent_block_assignment')
    )
    op.create_index(op.f('ix_agent_assignments_agent_id'), 'agent_assignments', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_assignments_block_id'), 'agent_assignments', ['block_id'], unique=False)
    op.create_index(op.f('ix_agent_assignments_block_type'), 'agent_assignments', ['block_type'], unique=False)
    op.create_table('agent_capabilities',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('group', sa.String(length=64), nullable=False),
    sa.Column('risk', sa.String(length=32), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'action', name='uq_agent_capability_action')
    )
    op.create_index(op.f('ix_agent_capabilities_action'), 'agent_capabilities', ['action'], unique=False)
    op.create_index(op.f('ix_agent_capabilities_agent_id'), 'agent_capabilities', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_capabilities_group'), 'agent_capabilities', ['group'], unique=False)
    op.create_index(op.f('ix_agent_capabilities_risk'), 'agent_capabilities', ['risk'], unique=False)
    op.create_table('agent_certificates',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('fingerprint_sha256', sa.String(length=255), nullable=False),
    sa.Column('serial_number', sa.String(length=255), nullable=False),
    sa.Column('certificate_pem', sa.Text(), nullable=False),
    sa.Column('valid_not_before', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_not_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_certificates_agent_id'), 'agent_certificates', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_certificates_fingerprint_sha256'), 'agent_certificates', ['fingerprint_sha256'], unique=False)
    op.create_index(op.f('ix_agent_certificates_serial_number'), 'agent_certificates', ['serial_number'], unique=False)
    op.create_index(op.f('ix_agent_certificates_status'), 'agent_certificates', ['status'], unique=False)
    op.create_table('agent_commands',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('command', sa.String(length=64), nullable=False),
    sa.Column('target', sa.JSON(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_commands_agent_id'), 'agent_commands', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_commands_status'), 'agent_commands', ['status'], unique=False)
    op.create_table('agent_endpoints',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('base_url', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_endpoints_agent_id'), 'agent_endpoints', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_endpoints_domain'), 'agent_endpoints', ['domain'], unique=False)
    op.create_index(op.f('ix_agent_endpoints_status'), 'agent_endpoints', ['status'], unique=False)
    op.create_table('agent_heartbeats',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_heartbeats_agent_id'), 'agent_heartbeats', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_heartbeats_observed_at'), 'agent_heartbeats', ['observed_at'], unique=False)
    op.create_table('agent_state_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_state_events_agent_id'), 'agent_state_events', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_state_events_created_at'), 'agent_state_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_state_events_event_type'), 'agent_state_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_agent_state_events_sequence'), 'agent_state_events', ['sequence'], unique=False)
    op.create_table('approval_decisions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=128), nullable=False),
    sa.Column('approval_id', sa.String(length=128), nullable=False),
    sa.Column('plan_hash', sa.String(length=255), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('decided_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_decisions_agent_id'), 'approval_decisions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_approval_decisions_approval_id'), 'approval_decisions', ['approval_id'], unique=False)
    op.create_index(op.f('ix_approval_decisions_decision'), 'approval_decisions', ['decision'], unique=False)
    op.create_index(op.f('ix_approval_decisions_job_id'), 'approval_decisions', ['job_id'], unique=False)
    op.create_index(op.f('ix_approval_decisions_plan_hash'), 'approval_decisions', ['plan_hash'], unique=False)
    op.create_table('approval_requests',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=128), nullable=False),
    sa.Column('approval_id', sa.String(length=128), nullable=False),
    sa.Column('plan_hash', sa.String(length=255), nullable=False),
    sa.Column('risk', sa.String(length=32), nullable=False),
    sa.Column('warning', sa.Text(), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requests_agent_id'), 'approval_requests', ['agent_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_approval_id'), 'approval_requests', ['approval_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_job_id'), 'approval_requests', ['job_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_plan_hash'), 'approval_requests', ['plan_hash'], unique=False)
    op.create_index(op.f('ix_approval_requests_status'), 'approval_requests', ['status'], unique=False)
    op.create_table('job_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_events_agent_id'), 'job_events', ['agent_id'], unique=False)
    op.create_index(op.f('ix_job_events_created_at'), 'job_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_job_events_event_type'), 'job_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_job_events_job_id'), 'job_events', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_events_sequence'), 'job_events', ['sequence'], unique=False)
    op.create_table('job_results',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_results_agent_id'), 'job_results', ['agent_id'], unique=False)
    op.create_index(op.f('ix_job_results_job_id'), 'job_results', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_results_status'), 'job_results', ['status'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=128), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('approver', sa.String(length=128), nullable=True),
    sa.Column('canceller', sa.String(length=128), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('plan', sa.JSON(), nullable=False),
    sa.Column('plan_hash', sa.String(length=255), nullable=True),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('error', sa.JSON(), nullable=False),
    sa.Column('log_reference', sa.String(length=255), nullable=True),
    sa.Column('agent_version', sa.String(length=64), nullable=True),
    sa.Column('sindri_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'job_id', name='uq_agent_job_id')
    )
    op.create_index(op.f('ix_jobs_action'), 'jobs', ['action'], unique=False)
    op.create_index(op.f('ix_jobs_agent_id'), 'jobs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_jobs_job_id'), 'jobs', ['job_id'], unique=False)
    op.create_index(op.f('ix_jobs_plan_hash'), 'jobs', ['plan_hash'], unique=False)
    op.create_index(op.f('ix_jobs_request_id'), 'jobs', ['request_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('revocation_records',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('certificate_serial', sa.String(length=255), nullable=False),
    sa.Column('certificate_fingerprint_sha256', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revocation_records_agent_id'), 'revocation_records', ['agent_id'], unique=False)
    op.create_index(op.f('ix_revocation_records_certificate_fingerprint_sha256'), 'revocation_records', ['certificate_fingerprint_sha256'], unique=False)
    op.create_index(op.f('ix_revocation_records_status'), 'revocation_records', ['status'], unique=False)
    op.create_table('subjects',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=16), nullable=False),
    sa.Column('object_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('image_data', sa.Text(), nullable=False),
    sa.Column('image_media_type', sa.String(length=64), nullable=False),
    sa.Column('runtime_type', sa.String(length=32), nullable=False),
    sa.Column('pod_id', sa.String(length=32), nullable=True),
    sa.Column('access_policy_id', sa.String(length=32), nullable=True),
    sa.Column('primary_route', sa.String(length=255), nullable=True),
    sa.Column('vless_uri_encrypted', sa.Text(), nullable=False),
    sa.Column('network_profile_version', sa.Integer(), nullable=False),
    sa.Column('system_tabs', sa.JSON(), nullable=False),
    sa.Column('system_tabs_profile_version', sa.Integer(), nullable=False),
    sa.Column('update_channel', sa.String(length=32), nullable=False),
    sa.Column('ui_policy', sa.JSON(), nullable=False),
    sa.Column('security_policy', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['access_policy_id'], ['access_policies.id'], ),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_entity_id'), 'subjects', ['entity_id'], unique=True)
    op.create_index(op.f('ix_subjects_kind'), 'subjects', ['kind'], unique=False)
    op.create_index(op.f('ix_subjects_object_id'), 'subjects', ['object_id'], unique=False)
    op.create_index(op.f('ix_subjects_pod_id'), 'subjects', ['pod_id'], unique=False)
    op.create_index(op.f('ix_subjects_runtime_type'), 'subjects', ['runtime_type'], unique=False)
    op.create_table('pod_provisioning_records',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('login', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('enrollment_token_hash', sa.String(length=255), nullable=False),
    sa.Column('enrollment_token_encrypted', sa.Text(), nullable=False),
    sa.Column('bundle_version', sa.String(length=64), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pod_provisioning_records_enrollment_token_hash'), 'pod_provisioning_records', ['enrollment_token_hash'], unique=True)
    op.create_index(op.f('ix_pod_provisioning_records_expires_at'), 'pod_provisioning_records', ['expires_at'], unique=False)
    op.create_index(op.f('ix_pod_provisioning_records_login'), 'pod_provisioning_records', ['login'], unique=False)
    op.create_index(op.f('ix_pod_provisioning_records_status'), 'pod_provisioning_records', ['status'], unique=False)
    op.create_index(op.f('ix_pod_provisioning_records_subject_id'), 'pod_provisioning_records', ['subject_id'], unique=False)
    op.create_table('pods',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.String(length=64), nullable=False),
    sa.Column('provisioning_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('login', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('host_id', sa.String(length=128), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('launcher_path', sa.String(length=1024), nullable=False),
    sa.Column('runtime_state', sa.JSON(), nullable=False),
    sa.Column('is_portable', sa.Boolean(), nullable=False),
    sa.Column('last_materialized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('public_key_pem', sa.Text(), nullable=False),
    sa.Column('identity_certificate', sa.Text(), nullable=False),
    sa.Column('certificate_fingerprint', sa.String(length=255), nullable=False),
    sa.Column('device_binding_fingerprint', sa.String(length=255), nullable=False),
    sa.Column('device_binding_status', sa.String(length=32), nullable=False),
    sa.Column('pod_version', sa.String(length=64), nullable=False),
    sa.Column('xray_version', sa.String(length=64), nullable=False),
    sa.Column('network_profile_version', sa.Integer(), nullable=False),
    sa.Column('system_tabs_profile_version', sa.Integer(), nullable=False),
    sa.Column('heartbeat_sequence', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provisioning_id'], ['pod_provisioning_records.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pods_certificate_fingerprint'), 'pods', ['certificate_fingerprint'], unique=False)
    op.create_index(op.f('ix_pods_device_binding_fingerprint'), 'pods', ['device_binding_fingerprint'], unique=False)
    op.create_index(op.f('ix_pods_host_id'), 'pods', ['host_id'], unique=False)
    op.create_index(op.f('ix_pods_last_seen_at'), 'pods', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_pods_login'), 'pods', ['login'], unique=False)
    op.create_index(op.f('ix_pods_provisioning_id'), 'pods', ['provisioning_id'], unique=False)
    op.create_index(op.f('ix_pods_status'), 'pods', ['status'], unique=False)
    op.create_index(op.f('ix_pods_subject_id'), 'pods', ['subject_id'], unique=False)
    op.create_table('launch_authorizations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.String(length=64), nullable=False),
    sa.Column('pod_id', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pod_id'], ['pods.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_launch_authorizations_decision'), 'launch_authorizations', ['decision'], unique=False)
    op.create_index(op.f('ix_launch_authorizations_pod_id'), 'launch_authorizations', ['pod_id'], unique=False)
    op.create_index(op.f('ix_launch_authorizations_subject_id'), 'launch_authorizations', ['subject_id'], unique=False)
    op.create_table('session_leases',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.String(length=64), nullable=True),
    sa.Column('pod_id', sa.String(length=32), nullable=True),
    sa.Column('agent_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('session_key_hash', sa.String(length=255), nullable=False),
    sa.Column('access_scope', sa.String(length=64), nullable=False),
    sa.Column('transport', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['pod_id'], ['pods.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_leases_access_scope'), 'session_leases', ['access_scope'], unique=False)
    op.create_index(op.f('ix_session_leases_agent_id'), 'session_leases', ['agent_id'], unique=False)
    op.create_index(op.f('ix_session_leases_pod_id'), 'session_leases', ['pod_id'], unique=False)
    op.create_index(op.f('ix_session_leases_status'), 'session_leases', ['status'], unique=False)
    op.create_index(op.f('ix_session_leases_subject_id'), 'session_leases', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_leases_subject_id'), table_name='session_leases')
    op.drop_index(op.f('ix_session_leases_status'), table_name='session_leases')
    op.drop_index(op.f('ix_session_leases_pod_id'), table_name='session_leases')
    op.drop_index(op.f('ix_session_leases_agent_id'), table_name='session_leases')
    op.drop_index(op.f('ix_session_leases_access_scope'), table_name='session_leases')
    op.drop_table('session_leases')
    op.drop_index(op.f('ix_launch_authorizations_subject_id'), table_name='launch_authorizations')
    op.drop_index(op.f('ix_launch_authorizations_pod_id'), table_name='launch_authorizations')
    op.drop_index(op.f('ix_launch_authorizations_decision'), table_name='launch_authorizations')
    op.drop_table('launch_authorizations')
    op.drop_index(op.f('ix_pods_subject_id'), table_name='pods')
    op.drop_index(op.f('ix_pods_status'), table_name='pods')
    op.drop_index(op.f('ix_pods_provisioning_id'), table_name='pods')
    op.drop_index(op.f('ix_pods_login'), table_name='pods')
    op.drop_index(op.f('ix_pods_last_seen_at'), table_name='pods')
    op.drop_index(op.f('ix_pods_host_id'), table_name='pods')
    op.drop_index(op.f('ix_pods_device_binding_fingerprint'), table_name='pods')
    op.drop_index(op.f('ix_pods_certificate_fingerprint'), table_name='pods')
    op.drop_table('pods')
    op.drop_index(op.f('ix_pod_provisioning_records_subject_id'), table_name='pod_provisioning_records')
    op.drop_index(op.f('ix_pod_provisioning_records_status'), table_name='pod_provisioning_records')
    op.drop_index(op.f('ix_pod_provisioning_records_login'), table_name='pod_provisioning_records')
    op.drop_index(op.f('ix_pod_provisioning_records_expires_at'), table_name='pod_provisioning_records')
    op.drop_index(op.f('ix_pod_provisioning_records_enrollment_token_hash'), table_name='pod_provisioning_records')
    op.drop_table('pod_provisioning_records')
    op.drop_index(op.f('ix_subjects_runtime_type'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_pod_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_object_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_kind'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_entity_id'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_revocation_records_status'), table_name='revocation_records')
    op.drop_index(op.f('ix_revocation_records_certificate_fingerprint_sha256'), table_name='revocation_records')
    op.drop_index(op.f('ix_revocation_records_agent_id'), table_name='revocation_records')
    op.drop_table('revocation_records')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_request_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_plan_hash'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_agent_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_action'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_job_results_status'), table_name='job_results')
    op.drop_index(op.f('ix_job_results_job_id'), table_name='job_results')
    op.drop_index(op.f('ix_job_results_agent_id'), table_name='job_results')
    op.drop_table('job_results')
    op.drop_index(op.f('ix_job_events_sequence'), table_name='job_events')
    op.drop_index(op.f('ix_job_events_job_id'), table_name='job_events')
    op.drop_index(op.f('ix_job_events_event_type'), table_name='job_events')
    op.drop_index(op.f('ix_job_events_created_at'), table_name='job_events')
    op.drop_index(op.f('ix_job_events_agent_id'), table_name='job_events')
    op.drop_table('job_events')
    op.drop_index(op.f('ix_approval_requests_status'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_plan_hash'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_job_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_approval_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_agent_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_approval_decisions_plan_hash'), table_name='approval_decisions')
    op.drop_index(op.f('ix_approval_decisions_job_id'), table_name='approval_decisions')
    op.drop_index(op.f('ix_approval_decisions_decision'), table_name='approval_decisions')
    op.drop_index(op.f('ix_approval_decisions_approval_id'), table_name='approval_decisions')
    op.drop_index(op.f('ix_approval_decisions_agent_id'), table_name='approval_decisions')
    op.drop_table('approval_decisions')
    op.drop_index(op.f('ix_agent_state_events_sequence'), table_name='agent_state_events')
    op.drop_index(op.f('ix_agent_state_events_event_type'), table_name='agent_state_events')
    op.drop_index(op.f('ix_agent_state_events_created_at'), table_name='agent_state_events')
    op.drop_index(op.f('ix_agent_state_events_agent_id'), table_name='agent_state_events')
    op.drop_table('agent_state_events')
    op.drop_index(op.f('ix_agent_heartbeats_observed_at'), table_name='agent_heartbeats')
    op.drop_index(op.f('ix_agent_heartbeats_agent_id'), table_name='agent_heartbeats')
    op.drop_table('agent_heartbeats')
    op.drop_index(op.f('ix_agent_endpoints_status'), table_name='agent_endpoints')
    op.drop_index(op.f('ix_agent_endpoints_domain'), table_name='agent_endpoints')
    op.drop_index(op.f('ix_agent_endpoints_agent_id'), table_name='agent_endpoints')
    op.drop_table('agent_endpoints')
    op.drop_index(op.f('ix_agent_commands_status'), table_name='agent_commands')
    op.drop_index(op.f('ix_agent_commands_agent_id'), table_name='agent_commands')
    op.drop_table('agent_commands')
    op.drop_index(op.f('ix_agent_certificates_status'), table_name='agent_certificates')
    op.drop_index(op.f('ix_agent_certificates_serial_number'), table_name='agent_certificates')
    op.drop_index(op.f('ix_agent_certificates_fingerprint_sha256'), table_name='agent_certificates')
    op.drop_index(op.f('ix_agent_certificates_agent_id'), table_name='agent_certificates')
    op.drop_table('agent_certificates')
    op.drop_index(op.f('ix_agent_capabilities_risk'), table_name='agent_capabilities')
    op.drop_index(op.f('ix_agent_capabilities_group'), table_name='agent_capabilities')
    op.drop_index(op.f('ix_agent_capabilities_agent_id'), table_name='agent_capabilities')
    op.drop_index(op.f('ix_agent_capabilities_action'), table_name='agent_capabilities')
    op.drop_table('agent_capabilities')
    op.drop_index(op.f('ix_agent_assignments_block_type'), table_name='agent_assignments')
    op.drop_index(op.f('ix_agent_assignments_block_id'), table_name='agent_assignments')
    op.drop_index(op.f('ix_agent_assignments_agent_id'), table_name='agent_assignments')
    op.drop_table('agent_assignments')
    op.drop_index(op.f('ix_system_settings_scope'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_pod_denylist_subject_id'), table_name='pod_denylist')
    op.drop_index(op.f('ix_pod_denylist_pod_id'), table_name='pod_denylist')
    op.drop_index(op.f('ix_pod_denylist_identifier_value'), table_name='pod_denylist')
    op.drop_index(op.f('ix_pod_denylist_identifier_type'), table_name='pod_denylist')
    op.drop_table('pod_denylist')
    op.drop_index(op.f('ix_objects_kind'), table_name='objects')
    op.drop_index(op.f('ix_objects_entity_id'), table_name='objects')
    op.drop_table('objects')
    op.drop_index(op.f('ix_controller_identity_status'), table_name='controller_identity')
    op.drop_index(op.f('ix_controller_identity_controller_id'), table_name='controller_identity')
    op.drop_table('controller_identity')
    op.drop_index(op.f('ix_certificate_denylist_fingerprint_sha256'), table_name='certificate_denylist')
    op.drop_index(op.f('ix_certificate_denylist_agent_id'), table_name='certificate_denylist')
    op.drop_table('certificate_denylist')
    op.drop_index(op.f('ix_backup_manifests_entity_type'), table_name='backup_manifests')
    op.drop_index(op.f('ix_backup_manifests_entity_id'), table_name='backup_manifests')
    op.drop_index(op.f('ix_backup_manifests_backup_id'), table_name='backup_manifests')
    op.drop_table('backup_manifests')
    op.drop_index(op.f('ix_audit_events_target_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_target_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_agents_status'), table_name='agents')
    op.drop_index(op.f('ix_agents_library_position'), table_name='agents')
    op.drop_index(op.f('ix_agents_identity_fingerprint'), table_name='agents')
    op.drop_index(op.f('ix_agents_host_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_enrollment_state'), table_name='agents')
    op.drop_index(op.f('ix_agents_domain'), table_name='agents')
    op.drop_index(op.f('ix_agents_certificate_serial'), table_name='agents')
    op.drop_index(op.f('ix_agents_agent_type'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_access_policies_status'), table_name='access_policies')
    op.drop_index(op.f('ix_access_policies_scope_type'), table_name='access_policies')
    op.drop_index(op.f('ix_access_policies_scope_id'), table_name='access_policies')
    op.drop_table('access_policies')
    # ### end Alembic commands ###
